<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>-->
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

	<PropertyGroup>
		<TieredCompilation>True</TieredCompilation>   
	</PropertyGroup>

  <ItemGroup>
    <None Remove="Weeks\week1\fileIO.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Weeks\week1\fileIO.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
